import json
from tqdm import tqdm

class LMB(object):
    def __init__(self, location, json_obj=None):
            """
                    Instantiates the LMB object.

                            Parameters
                                    ----------
                                            location (string): location of the json file.
                                                    json_obj (list): Optional direct injection of json object.
                                                            """
                                                                    if json_obj is None:
                                                                                with open(location, "r") as f:
                                                                                                self.json = json.load(f)
                                                                                                        else:
                                                                                                                    self.json = json_obj

                                                                                                                            self.samples = self.__create_samples__(self.json)

                                                                                                                                def __create_samples__(self, samples):
                                                                                                                                        created_samples = []
                                                                                                                                                # Iterate through the list of dictionaries in the JSON
                                                                                                                                                        for sample in samples:
                                                                                                                                                                    created_samples.append(Sample(
                                                                                                                                                                                    original_words=sample['original_words'],
                                                                                                                                                                                                    replaced_words=sample['replaced_words'],
                                                                                                                                                                                                                    original_sentence=sample['original_sentence'],
                                                                                                                                                                                                                                    replaced_sentence=sample['replaced_sentence'],
                                                                                                                                                                                                                                                    group=sample['group'],
                                                                                                                                                                                                                                                                    occupation=sample['occupation'],
                                                                                                                                                                                                                                                                                    occupation_gender=sample['occupation_gender']
                                                                                                                                                                                                                                                                                                ))
                                                                                                                                                                                                                                                                                                        return created_samples

                                                                                                                                                                                                                                                                                                            def get_samples(self):
                                                                                                                                                                                                                                                                                                                    return self.samples


                                                                                                                                                                                                                                                                                                                    class Sample(object):
                                                                                                                                                                                                                                                                                                                        def __init__(self, original_words, replaced_words, original_sentence, 
                                                                                                                                                                                                                                                                                                                                         replaced_sentence, group, occupation, occupation_gender):
                                                                                                                                                                                                                                                                                                                                                 """ 
                                                                                                                                                                                                                                                                                                                                                         Stores the data for a single entry from the JSON.
                                                                                                                                                                                                                                                                                                                                                                 """
                                                                                                                                                                                                                                                                                                                                                                         # You can use convert_to_list here if you expect comma-separated strings
                                                                                                                                                                                                                                                                                                                                                                                 # For now, we assign the values directly based on your JSON format.
                                                                                                                                                                                                                                                                                                                                                                                         self.original_words = original_words
                                                                                                                                                                                                                                                                                                                                                                                                 self.replaced_words = replaced_words
                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                 self.original_sentence = original_sentence
                                                                                                                                                                                                                                                                                                                                                                                                                         self.replaced_sentence = replaced_sentence
                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                         self.group = group
                                                                                                                                                                                                                                                                                                                                                                                                                                                 self.occupation = occupation
                                                                                                                                                                                                                                                                                                                                                                                                                                                         self.occupation_gender = occupation_gender

                                                                                                                                                                                                                                                                                                                                                                                                                                                             def convert_to_list(self, input_string):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Helper to split comma-separated strings into lists if necessary.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Usage: self.original_words = self.convert_to_list(original_words)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             """
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if not isinstance(input_string, str):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 return input_string
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         sanitized_string = input_string.replace("'", "").strip()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 return [item.strip() for item in sanitized_string.split(',')] if ',' in sanitized_string else [sanitized_string]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     def __str__(self):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             s = (f"Original: {self.original_sentence}\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          f"Replaced: {self.replaced_sentence}\n"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       f"Occupation: {self.occupation} ({self.occupation_gender})")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               return s